// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy6ixNkcmsoZTq8_3mbOzC5wTe3sbuFE8',
    appId: '1:395022899006:web:7045a86760da19c9783e6f',
    messagingSenderId: '395022899006',
    projectId: 'tablenow-a5e52',
    authDomain: 'tablenow-a5e52.firebaseapp.com',
    storageBucket: 'tablenow-a5e52.firebasestorage.app',
    measurementId: 'G-RJBD3CM9RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrPEEaqFCuPvCyAH1TOhHyOgFagXucn7o',
    appId: '1:395022899006:android:d13d750f56b527ce783e6f',
    messagingSenderId: '395022899006',
    projectId: 'tablenow-a5e52',
    storageBucket: 'tablenow-a5e52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNl9nZKz0H6PMLQ_CKrSc6n_gywmZCtQ',
    appId: '1:395022899006:ios:897b8729679c1ba0783e6f',
    messagingSenderId: '395022899006',
    projectId: 'tablenow-a5e52',
    storageBucket: 'tablenow-a5e52.firebasestorage.app',
    iosBundleId: 'com.example.tablenowapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNl9nZKz0H6PMLQ_CKrSc6n_gywmZCtQ',
    appId: '1:395022899006:ios:897b8729679c1ba0783e6f',
    messagingSenderId: '395022899006',
    projectId: 'tablenow-a5e52',
    storageBucket: 'tablenow-a5e52.firebasestorage.app',
    iosBundleId: 'com.example.tablenowapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy6ixNkcmsoZTq8_3mbOzC5wTe3sbuFE8',
    appId: '1:395022899006:web:8ff1a84deb9f24fc783e6f',
    messagingSenderId: '395022899006',
    projectId: 'tablenow-a5e52',
    authDomain: 'tablenow-a5e52.firebaseapp.com',
    storageBucket: 'tablenow-a5e52.firebasestorage.app',
    measurementId: 'G-5CB09M4HG4',
  );
}
